### PR TITLE
Add items to Cart

### PR DESCRIPTION
**Pull request by GeneralStarlord**
New class added for adding an item into cart

### CODE REVIEW

**Review by hannahst17 — COMMENTED** [review]
Can you explain what you're doing with the cookies please? 👍

**Comment by GeneralStarlord** [comment]
Reply

**Comment by GeneralStarlord** [comment]
Extracted the cookies on the website so that it would remember my settings when attempting to add an item to the cart.

**Review by hannahst17 — APPROVED** [review]
Happy for this to go in

**Review by Saghir-ayub — APPROVED** [review]
Looks good to me

**Pull request merged**
