### PR TITLE
added shopping cart test, needs assertions

### PR DESCRIPTION
**Pull request by Saghir-ayub**
added shopping cart to page objects

### CODE REVIEW

**Review by hannahst17 — APPROVED** [review]
Looks good to me

**Comment by Marhamatel** [comment]
looks useful

**Review by GeneralStarlord — COMMENTED** [review]
Do we still need the print out lines on 36 and 37?

**Comment by Saghir-ayub** [comment]
> Do we still need the print out lines on 36 and 37?

updated

**Review by GeneralStarlord — APPROVED** [review]
Cool looks all good now

**Review by hannahst17 — APPROVED** [review]
10/10

**Pull request merged**
