### PR TITLE
added service objects and page tests

### PR DESCRIPTION
**Pull request by Saghir-ayub**
good luck, added in base page, object pages and some tests

### CODE REVIEW

**Review by hannahst17 — COMMENTED** [review]
Looks really good. I like your use of the page object model. Only question is whether you could use query parameters with "?controller=my-account"? where you have it as 'extension'?

**Comment by Saghir-ayub** [comment]
> Looks really good. I like your use of the page object model. Only question is whether you could use query parameters with "?controller=my-account"? where you have it as 'extension'?

image
should be able to add it here

**Review by hannahst17 — APPROVED** [review]
Happy for this to go in

**Review by joejross — APPROVED** [review]

**Review by GeneralStarlord — APPROVED** [review]
All looks good to me

**Pull request merged**
