### PR TITLE
Added a test to check search bar functionality

### PR DESCRIPTION
**Pull request by hannahst17**

### CODE REVIEW

**Review by GeneralStarlord — COMMENTED** [review]
Is this checking that the search bar can accessed?

**Comment by Saghir-ayub** [comment]
this can probably be changed to something like:
response = httpRequest.queryparam("controller", "search").queryparam("s", "top").when().get() 

then do something with the response like asserting response.statuscode() is 200

**Comment by hannahst17** [comment]
With the query parameters it should search for 'top'

**Comment by hannahst17** [comment]
Will give that a try

**Comment by Saghir-ayub** [comment]
also probably want to add this to the homepage serviceObject then in this file just do homePage.checkSearch() could probably do homePage.checkSearch(String searchEntry) and make it a parameter but thats for later reusability of the request

**Review by joejross — APPROVED** [review]
Looks good!

**Pull request closed without merging**
